@extends('admin.layout')

@section('title', isset($market) ? 'Edit Market' : 'Tambah Market')
@section('header', isset($market) ? 'Edit Market' : 'Tambah Market')

@push('styles')

<style>
    .cards-grid {
        display: grid;
        grid-template-columns: repeat(auto-fill, minmax(160px, 1fr));
        gap: 15px;
        margin-bottom: 20px;
    }
    .card-slot {
        width: 100%;
        aspect-ratio: 3/4;
        border-radius: 8px;
        position: relative;
        transition: 0.2s;
    }
    .card-slot.empty {
        background-color: #f8f9fa;
        border: 1px solid #e0e0e0;
    }
    .card-slot.add-new {
        border: 2px dashed #b0b0b0;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        cursor: pointer;
        color: #888;
        background-color: transparent;
    }
    .card-slot.add-new:hover {
        border-color: #0056b3;
        color: #0056b3;
        background-color: #f0f7ff;
    }
    .card-slot.filled {
        border: 1px solid #e0e0e0;
        overflow: hidden;
        background: #fff;
        cursor: pointer;
        box-shadow: 0 2px 5px rgba(0,0,0,0.05);
    }
    .card-slot.filled img {
        width: 100%;
        height: 70%;
        object-fit: cover;
    }
    .card-slot.filled .card-title {
        padding: 10px;
        font-size: 13px;
        font-weight: bold;
        text-align: center;
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
        border-top: 1px solid #eee;
    }
    .card-overlay {
        position: absolute;
        top: 0; left: 0; right: 0; bottom: 0;
        background: rgba(0,0,0,0.6);
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        gap: 10px;
        opacity: 0;
        transition: 0.2s;
        border-radius: 8px;
    }
    .card-slot.filled:hover .card-overlay {
        opacity: 1;
    }
    .hidden-card-input { display: none; }
</style>
@endpush

@section('content')
<div class="card shadow-sm">
    <div class="card-header bg-white">
        <h6 class="m-0 font-weight-bold text-primary">{{ isset($market) ? 'Edit Data Market' : 'Form Tambah Market Baru' }}</h6>
    </div>
    <div class="card-body">
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul class="mb-0">
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <form action="{{ isset($market) ? route('admin.markets.update', $market->id) : route('admin.markets.store') }}" method="POST" enctype="multipart/form-data" id="marketForm">
            @csrf
            @if(isset($market))
                @method('PUT')
            @endif

            <div class="row">
                <div class="col-md-4">
                    <div class="mb-3">
                        @include('admin.markets._market_image_upload', ['name' => 'banner_image', 'label' => 'Gambar Banner Atas', 'default' => $market->banner_image ?? ''])
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="mb-3">
                        <label class="form-label fw-bold">Judul Halaman <span class="text-danger">*</span></label>
                        <input type="text" class="form-control" name="title" value="{{ old('title', $market->title ?? '') }}" required>
                    </div>
                    <div class="mb-3">
                        <label class="form-label fw-bold">Sub-judul <span class="text-danger">*</span></label>
                        <input type="text" class="form-control" name="subtitle" value="{{ old('subtitle', $market->subtitle ?? 'Our Markets') }}" required>
                    </div>

                </div>
            </div>

            <h5 class="fw-bold mt-5 mb-3 border-bottom pb-2">Daftar Produk/Kategori Market</h5>
            <p class="text-muted small mb-3">Maksimal 8 foto produk. Klik kotak putus-putus untuk menambah. Arahkan kursor pada kotak untuk mengedit atau menghapus.</p>
            
            <div class="cards-grid" id="cards-grid">
                <!-- Grid items generated by JS -->
            </div>

            <!-- HIDDEN INPUTS AREA -->
            <div id="hidden-cards-container" class="d-none">
                @for($i = 0; $i < 8; $i++)
                    @php
                        $card = isset($market) && isset($market->cards[$i]) ? $market->cards[$i] : null;
                    @endphp
                    <div class="hidden-card-input" data-index="{{ $i }}" id="hidden-card-{{ $i }}">
                        <input type="text" name="cards[{{ $i }}][title]" value="{{ $card['title'] ?? '' }}" class="hidden-title">
                        <textarea name="cards[{{ $i }}][subtitle]" class="hidden-subtitle">{{ $card['subtitle'] ?? '' }}</textarea>
                        <input type="hidden" name="cards[{{ $i }}][old_image]" value="{{ $card['image'] ?? '' }}" class="hidden-old-image">
                        <div id="card-image-upload-{{ $i }}">
                            @include('admin.markets._market_image_upload', ['name' => "cards[$i][image]", 'label' => 'Gambar Kartu', 'default' => $card['image'] ?? ''])
                        </div>
                    </div>
                @endfor
            </div>

            <hr>
            <div class="d-flex justify-content-between">
                <a href="{{ route('admin.markets.index') }}" class="btn btn-secondary">Kembali</a>
                <button type="submit" class="btn btn-success"><i class="fas fa-save me-1"></i> Simpan Market</button>
            </div>
        </form>
    </div>
</div>

<!-- Modal Edit Kartu -->
<div class="modal fade" id="cardModal" tabindex="-1" aria-hidden="true" data-bs-backdrop="static">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="cardModalTitle">Tambah Produk/Kategori</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
            <div class="modal-body">
        <div id="modal-error-msg" class="alert alert-danger d-none py-2 mb-3" style="font-size: 0.85rem;"><i class="fas fa-exclamation-circle me-1"></i> Mohon lengkapi semua data! Gambar, Judul, dan Deskripsi wajib diisi.</div>
        <div id="modal-file-input-container">
            <!-- File input component will be moved here dynamically -->
        </div>
        <div class="mb-3 mt-3">
            <label class="form-label fw-bold">Judul Kartu</label>
            <input type="text" class="form-control" id="modal-title-input" placeholder="Masukkan judul produk...">
        </div>
        <div class="mb-3">
            <label class="form-label fw-bold">Deskripsi Singkat</label>
            <textarea class="form-control" id="modal-subtitle-input" rows="3" placeholder="Masukkan deskripsi singkat..."></textarea>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Batal</button>
        <button type="button" class="btn btn-primary" id="btn-save-modal">Simpan Data</button>
      </div>
    </div>
  </div>
</div>

@endsection

@push('scripts')
<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>

<script>
            function previewImage(input, previewId) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function(e) {
                    $('#' + previewId).attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }

    $(document).ready(function() {


        const MAX_CARDS = 8;
        let cardsData = [];
        let currentEditingArrayIndex = -1;
        let activeHiddenIndex = -1; // The physical DOM hidden container index

        // Initialize cardsData from DOM
        for(let i=0; i<MAX_CARDS; i++) {
            let container = $('#hidden-card-' + i);
            let title = container.find('.hidden-title').val();
            let oldImage = container.find('.hidden-old-image').val();
            
            // If it has a title or old image, it's considered an active card
            if(title || oldImage) {
                cardsData.push({
                    domIndex: i, // which hidden container it belongs to
                    title: title,
                    subtitle: container.find('.hidden-subtitle').val()
                });
            }
        }

        function renderGrid() {
            let html = '';
            for(let i=0; i<MAX_CARDS; i++) {
                if (i < cardsData.length) {
                    let card = cardsData[i];
                    
                    // Fetch current preview image from the DOM component
                    let imgElem = $('#card-image-upload-' + card.domIndex).find('img');
                    let imgSrc = imgElem.attr('src') || 'https://placehold.co/600x400?text=Foto';

                    html += `
                    <div class="card-slot filled">
                        <img src="${imgSrc}">
                        <div class="card-title">${card.title || 'Tanpa Judul'}</div>
                        <div class="card-overlay">
                            <button type="button" class="btn btn-sm btn-light" onclick="openModal(${i})"><i class="fas fa-edit"></i> Edit</button>
                            <button type="button" class="btn btn-sm btn-danger" onclick="deleteCard(${i})"><i class="fas fa-trash"></i> Hapus</button>
                        </div>
                    </div>`;
                } else if (i === cardsData.length) {
                    // Render "Add" box at the current tail
                    html += `
                    <div class="card-slot add-new" onclick="openModal(-1)">
                        <i class="fas fa-camera fa-2x mb-2"></i>
                        <span>Tambah foto</span>
                    </div>`;
                } else {
                    // Empty slot
                    html += `<div class="card-slot empty"></div>`;
                }
            }
            $('#cards-grid').html(html);
        }

        window.openModal = function(arrayIndex) {
            // Restore any previously moved file input just in case modal was closed abruptly
            restoreFileInput();

            if (arrayIndex === -1) {
                // Add new
                $('#cardModalTitle').text('Tambah Produk/Kategori Baru');
                currentEditingArrayIndex = cardsData.length;
                
                // Find an unused domIndex (one that isn't in cardsData)
                let usedIndices = cardsData.map(c => c.domIndex);
                activeHiddenIndex = -1;
                for(let i=0; i<MAX_CARDS; i++) {
                    if(!usedIndices.includes(i)) {
                        activeHiddenIndex = i;
                        break;
                    }
                }
                
                if(activeHiddenIndex === -1) {
                    alert('Maksimal kartu telah tercapai!');
                    return;
                }

                // Clear the hidden inputs for this new slot
                let container = $('#hidden-card-' + activeHiddenIndex);
                container.find('.hidden-title').val('');
                container.find('.hidden-subtitle').val('');
                container.find('.hidden-old-image').val('');
                container.find('input[type="file"]').val('');
                // reset preview using the ID generated by the partial
                let cleanId = container.find('input[type="file"]').attr('id').replace('input_', 'preview_');
                $('#' + cleanId).attr('src', 'https://placehold.co/600x400?text=Pilih+Foto');

                $('#modal-title-input').val('');
                $('#modal-subtitle-input').val('');

            } else {
                // Edit existing
                $('#cardModalTitle').text('Edit Produk/Kategori');
                currentEditingArrayIndex = arrayIndex;
                activeHiddenIndex = cardsData[arrayIndex].domIndex;

                let container = $('#hidden-card-' + activeHiddenIndex);
                $('#modal-title-input').val(container.find('.hidden-title').val());
                $('#modal-subtitle-input').val(container.find('.hidden-subtitle').val());
            }

            // Move the file upload UI component into the modal
            $('#modal-file-input-container').append($('#card-image-upload-' + activeHiddenIndex));

            $('#cardModal').modal('show');
        };

        function restoreFileInput() {
            if (activeHiddenIndex !== -1) {
                // move it back from modal to hidden container
                $('#hidden-card-' + activeHiddenIndex).append($('#card-image-upload-' + activeHiddenIndex));
            }
        }

        // When modal is closed without saving (batal/x button)
        $('#cardModal').on('hidden.bs.modal', function () {
            restoreFileInput();
            activeHiddenIndex = -1;
            renderGrid();
        });

        $('#btn-save-modal').click(function() {
            let title = $('#modal-title-input').val().trim();
            let subtitle = $('#modal-subtitle-input').val().trim();
            
            // Check if there is a file selected or an old image exists
            let hasFile = $('#card-image-upload-' + activeHiddenIndex).find('input[type="file"]').val() !== '';
            let hasOldImage = $('#hidden-card-' + activeHiddenIndex).find('.hidden-old-image').val() !== '';
            
            // Validation
            if (title === '' || subtitle === '' || (!hasFile && !hasOldImage)) {
                $('#modal-error-msg').removeClass('d-none');
                return; // Stop execution
            } else {
                $('#modal-error-msg').addClass('d-none');
            }
            
            // Move file component back
            restoreFileInput();
            
            // Update hidden values
            let container = $('#hidden-card-' + activeHiddenIndex);
            container.find('.hidden-title').val(title);
            container.find('.hidden-subtitle').val(subtitle);

            if (currentEditingArrayIndex === cardsData.length) {
                // Was adding new
                cardsData.push({
                    domIndex: activeHiddenIndex,
                    title: title,
                    subtitle: subtitle
                });
            } else {
                // Was editing
                cardsData[currentEditingArrayIndex].title = title;
                cardsData[currentEditingArrayIndex].subtitle = subtitle;
            }

            activeHiddenIndex = -1; // clear
            $('#cardModal').modal('hide'); // renderGrid is called on hidden event, but we can call it here too
            renderGrid();
        });

        window.deleteCard = function(arrayIndex) {
            if(confirm('Hapus kartu ini?')) {
                let domIdx = cardsData[arrayIndex].domIndex;
                
                // Remove from tracking array
                cardsData.splice(arrayIndex, 1);
                
                // Clear the physical hidden inputs so they aren't submitted
                let container = $('#hidden-card-' + domIdx);
                container.find('.hidden-title').val('');
                container.find('.hidden-subtitle').val('');
                container.find('.hidden-old-image').val('');
                container.find('input[type="file"]').val('');

                // IMPORTANT: Reorder the `name` attributes of all active hidden containers
                // so they submit as cards[0], cards[1], cards[2] without gaps!
                for(let i=0; i<MAX_CARDS; i++) {
                    let cont = $('#hidden-card-' + i);
                    
                    // Find if this domIndex is still active
                    let currentPos = -1;
                    for(let j=0; j<cardsData.length; j++) {
                        if(cardsData[j].domIndex === i) {
                            currentPos = j;
                            break;
                        }
                    }

                    if (currentPos !== -1) {
                        // It is active, set name to cards[currentPos]
                        cont.find('.hidden-title').attr('name', `cards[${currentPos}][title]`);
                        cont.find('.hidden-subtitle').attr('name', `cards[${currentPos}][subtitle]`);
                        cont.find('.hidden-old-image').attr('name', `cards[${currentPos}][old_image]`);
                        cont.find('input[type="file"]').attr('name', `cards[${currentPos}][image]`);
                    } else {
                        // It is inactive, set name to cards[i] (or anything, since values are empty it won't matter, but keeping consistent is good)
                        cont.find('.hidden-title').attr('name', `cards[${i}][title]`);
                        cont.find('.hidden-subtitle').attr('name', `cards[${i}][subtitle]`);
                        cont.find('.hidden-old-image').attr('name', `cards[${i}][old_image]`);
                        cont.find('input[type="file"]').attr('name', `cards[${i}][image]`);
                    }
                }

                renderGrid();
            }
        };

        // Render initial state
        renderGrid();
    });
</script>
@endpush